apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-job-cnn-benchmark"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: your-project/stacks-pytorch-kf-mkl:v0.6.0
    Worker:
      replicas: 1
      restartPolicy: Never 
      template:
        spec:
          containers: 
            - name: pytorch
              image: your-project/stacks-pytorch-kf-mkl:v0.6.0
