
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-dn-volume
spec:
  storageClassName: ""
  capacity:
    storage: 600G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: hc-data-disk
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-dn-claim
spec:
  storageClassName: ""
  volumeName: hdfs-dn-volume
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 600G

