apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-nn-volume
  labels:
    pv: hdfs-nn-claim
    component: hdfs-nn
spec:
  storageClassName: ""
  capacity:
    storage: 600G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: hc-data-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-nn-claim
  labels:
    component: hdfs-nn
spec:
  selector:
      matchLabels:
        pv: hdfs-nn-claim
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 600G

